"""Discover and register an installed optional codebase MCP server on SessionStart.

source: ADR-0584"""

from __future__ import annotations

import logging
import os
import shutil
import sys

from mcp_server.infrastructure.upstream_identity import (
    BINARY_NAMES,
    CANONICAL_PLUGIN,
    PLUGIN_KEY_BINARIES,
    built_binary_relatives,
)
from pathlib import Path
from typing import Optional

from mcp_server.infrastructure.config import MCP_CONNECTIONS_PATH
from mcp_server.infrastructure.file_io import read_json, write_json
from mcp_server.shared.platform import home_dir

logger = logging.getLogger(__name__)

# Binary name candidates on PATH, cheapest check first.
_BINARY_CANDIDATES = ("cortex-pipeline", *BINARY_NAMES)

# source: ADR-0584
_SOURCE_DIRS = (
    f"../anthropic/{CANONICAL_PLUGIN}",
    f"../../anthropic/{CANONICAL_PLUGIN}",
    f"../{CANONICAL_PLUGIN}",
    "../anthropic/ai-architect-mcp-codebase",
    "../../anthropic/ai-architect-mcp-codebase",
    "../ai-architect-mcp-codebase",
)

# source: ADR-0584
_BUILT_RELATIVE = built_binary_relatives()

# ── Marketplace install (canonical) ─────────────────────────────────────

# source: ADR-0584
_INSTALLED_PLUGINS_PATH = home_dir() / ".claude" / "plugins" / "installed_plugins.json"
# source: ADR-0584
_AP_PLUGIN_KEYS = PLUGIN_KEY_BINARIES


def _marketplace_pipeline_binary() -> Optional[str]:
    """Resolve the AP binary from the marketplace install, or None.

    source: ADR-0584"""
    try:
        data = read_json(_INSTALLED_PLUGINS_PATH) or {}
        plugins = data.get("plugins") or {}
        for plugin_key, binary_name in _AP_PLUGIN_KEYS:
            for entry in plugins.get(plugin_key) or []:
                install_path = entry.get("installPath")
                if not install_path:
                    continue
                binary = Path(install_path) / "target" / "release" / binary_name
                if binary.is_file() and os.access(binary, os.X_OK):
                    return str(binary)
    except Exception as exc:  # noqa: BLE001 — plugin-registry probe; failure is logged, discovery reports not-installed
        logger.debug("AP plugin discovery failed (non-fatal): %s", exc)
        return None
    return None


# ── Install paths (shared with pipeline_installer) ──────────────────────

# source: ADR-0584
_INSTALL_SRC_DIR = (
    home_dir() / ".claude" / "methodology" / "src" / "ai-architect-mcp-codebase"
)
_INSTALL_BIN_DIR = home_dir() / ".claude" / "methodology" / "bin"
_INSTALL_SYMLINK = _INSTALL_BIN_DIR / "mcp-server"

# source: ADR-0584
_AUTOGEN_COMMENT = (
    "Auto-generated by Cortex pipeline_discovery. Customize freely — "
    "Cortex only adds missing server entries and backfills missing fields "
    "(e.g. callTimeoutMs); it never overwrites a value you set."
)
_LEGACY_AUTOGEN_COMMENT = (
    "Auto-generated by Cortex pipeline_discovery. Customize freely — "
    "Cortex only adds missing server entries, never overwrites."
)


def discover_pipeline_command() -> Optional[list[str]]:
    """Return [command, *args] for the pipeline MCP server, or None.

        None means "no pipeline found" — callers should leave the mcp
        config alone and let ingest_codebase fail with the standard
        McpConnectionError when invoked (ingestion is explicitly opt-in).

    source: ADR-0584"""
    # Canonical: the marketplace-installed AP plugin.
    marketplace = _marketplace_pipeline_binary()
    if marketplace:
        return [marketplace]

    # source: ADR-0584
    if _INSTALL_SYMLINK.exists() and os.access(_INSTALL_SYMLINK, os.X_OK):
        return [str(_INSTALL_SYMLINK)]

    for name in _BINARY_CANDIDATES:
        path = shutil.which(name)
        if path:
            return [path]

    for source in _SOURCE_DIRS:
        root = Path(source).expanduser().resolve()
        if not root.is_dir():
            continue
        for rel in _BUILT_RELATIVE:
            built = root / rel
            # source: ADR-0584
            if built.is_file() and (
                sys.platform == "win32" or built.stat().st_mode & 0o111
            ):
                return [str(built)]

    return None


def _backfill_call_timeout(path: Path, existing: dict, entry: dict) -> None:
    """Add a MISSING ``callTimeoutMs`` to a valid pre-existing entry.

    source: ADR-0584"""
    servers = dict(existing.get("servers") or {})
    servers["codebase"] = {**entry, "callTimeoutMs": 0}
    updated = {**existing, "servers": servers}
    if updated.get("_comment") == _LEGACY_AUTOGEN_COMMENT:
        updated["_comment"] = _AUTOGEN_COMMENT
    try:
        write_json(path, updated)
    except Exception as exc:  # noqa: BLE001 — last-resort boundary — failure is logged; degraded mode continues
        logger.warning("Failed to backfill callTimeoutMs in %s: %s", path, exc)


def ensure_pipeline_connection() -> dict:
    """Write the ``codebase`` entry into mcp-connections.json when absent.

    Returns a small audit dict describing what happened:
      action: "wrote_config" | "added_codebase" | "already_configured"
              | "no_pipeline_found"
      path:   path to the config file (always)
      binary: resolved pipeline binary path (when discovered)

    Idempotent. Safe to call every SessionStart.
    """
    path = Path(MCP_CONNECTIONS_PATH)
    command = discover_pipeline_command()
    existing = read_json(path) or {}

    existing_codebase = existing.get("servers", {}).get("codebase")
    if existing_codebase:
        configured_cmd = existing_codebase.get("command") or ""
        # source: ADR-0584
        if (
            configured_cmd
            and Path(configured_cmd).exists()
            and os.access(configured_cmd, os.X_OK)
        ):
            if "callTimeoutMs" not in existing_codebase:
                _backfill_call_timeout(path, existing, existing_codebase)
            return {
                "action": "already_configured",
                "path": str(path),
                "binary": configured_cmd,
            }
        # source: ADR-0584
        servers = dict(existing.get("servers") or {})
        servers.pop("codebase", None)
        existing = {**existing, "servers": servers}
        try:
            write_json(path, existing)
        except Exception as exc:  # noqa: BLE001 — last-resort boundary — failure is logged; degraded mode continues
            logger.warning(
                "Failed to purge stale codebase entry from %s: %s", path, exc
            )

    # source: ADR-0584
    if command is None:
        from mcp_server.infrastructure.pipeline_installer import install_pipeline  # noqa: PLC0415 — import cycle with mcp_server.infrastructure.pipeline_installer; a top-level import fails at boot

        install_result = install_pipeline()
        if install_result.get("action") == "installed":
            command = discover_pipeline_command()

    if command is None:
        return {"action": "no_pipeline_found", "path": str(path)}

    # Merge into existing config (preserving other servers) or create fresh.
    config = dict(existing)
    servers = dict(config.get("servers") or {})
    servers["codebase"] = {
        "command": command[0],
        "args": command[1:],
        "env": {},
        # source: ADR-0584
        "callTimeoutMs": 0,
    }
    config["servers"] = servers
    config.setdefault("_comment", _AUTOGEN_COMMENT)

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_json(path, config)
    except Exception as exc:  # noqa: BLE001 — last-resort boundary — failure is logged; degraded mode continues
        logger.warning("Failed to write %s: %s", path, exc)
        return {
            "action": "write_failed",
            "path": str(path),
            "binary": command[0],
            "error": str(exc),
        }

    return {
        "action": "wrote_config" if not existing else "added_codebase",
        "path": str(path),
        "binary": command[0],
    }
