"""Discover the ai-automatised-pipeline MCP server and wire it into
Cortex's mcp-connections.json automatically.

Runs on SessionStart so users who have the pipeline installed get the
``codebase`` MCP server wired up without manual config editing. The
discovery mirrors ``cortex-doctor``'s optional-capability probe:

  1. Binaries on PATH: ``cortex-pipeline``, ``automatised-pipeline``,
     ``ai-automatised-pipeline``, ``ai-architect-mcp``.
  2. Sibling git checkout at ``../anthropic/ai-automatised-pipeline``
     with a built Cargo release binary at
     ``target/release/ai-architect-mcp``.
  3. Otherwise: no change to mcp-connections.json.

If the file already exists AND already has a ``codebase`` server entry,
we leave it alone — users who customized their config keep their
customization. We only write when the config is missing entirely OR
the ``codebase`` key is absent.

Source: user directive "detected and guided, not all users will have a
use of it". Pipeline is optional.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Optional

from mcp_server.infrastructure.config import MCP_CONNECTIONS_PATH
from mcp_server.infrastructure.file_io import read_json, write_json

logger = logging.getLogger(__name__)

# Binary name candidates on PATH, cheapest check first.
_BINARY_CANDIDATES = (
    "cortex-pipeline",
    "automatised-pipeline",
    "ai-automatised-pipeline",
    "ai-architect-mcp",
)

# Common source-checkout locations. Relative to each user's working dir
# (the MCP server runs in the user's project root, so `..` is their
# parent directory — a common monorepo sibling layout).
_SOURCE_DIRS = (
    "../anthropic/ai-automatised-pipeline",
    "../../anthropic/ai-automatised-pipeline",
    "../ai-automatised-pipeline",
)

_BUILT_RELATIVE = ("target/release/ai-architect-mcp",)


def discover_pipeline_command() -> Optional[list[str]]:
    """Return [command, *args] for the pipeline MCP server, or None.

    None means "no pipeline found" — callers should leave the mcp
    config alone and let ingest_codebase fail with the standard
    McpConnectionError when invoked (ingestion is explicitly opt-in).
    """
    for name in _BINARY_CANDIDATES:
        path = shutil.which(name)
        if path:
            return [path]

    for source in _SOURCE_DIRS:
        root = Path(source).expanduser().resolve()
        if not root.is_dir():
            continue
        for rel in _BUILT_RELATIVE:
            built = root / rel
            if built.is_file() and built.stat().st_mode & 0o111:
                return [str(built)]

    return None


def ensure_pipeline_connection() -> dict:
    """Write the ``codebase`` entry into mcp-connections.json when absent.

    Returns a small audit dict describing what happened:
      action: "wrote_config" | "added_codebase" | "already_configured"
              | "no_pipeline_found"
      path:   path to the config file (always)
      binary: resolved pipeline binary path (when discovered)

    Idempotent. Safe to call every SessionStart.
    """
    path = Path(MCP_CONNECTIONS_PATH)
    command = discover_pipeline_command()
    existing = read_json(path) or {}

    if existing.get("servers", {}).get("codebase"):
        return {
            "action": "already_configured",
            "path": str(path),
            "binary": existing["servers"]["codebase"].get("command"),
        }

    if command is None:
        return {"action": "no_pipeline_found", "path": str(path)}

    # Merge into existing config (preserving other servers) or create fresh.
    config = dict(existing)
    servers = dict(config.get("servers") or {})
    servers["codebase"] = {
        "command": command[0],
        "args": command[1:],
        "env": {},
    }
    config["servers"] = servers
    config.setdefault(
        "_comment",
        "Auto-generated by Cortex pipeline_discovery. Customize freely — "
        "Cortex only adds missing server entries, never overwrites.",
    )

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_json(path, config)
    except Exception as exc:
        logger.warning("Failed to write %s: %s", path, exc)
        return {
            "action": "write_failed",
            "path": str(path),
            "binary": command[0],
            "error": str(exc),
        }

    return {
        "action": "wrote_config" if not existing else "added_codebase",
        "path": str(path),
        "binary": command[0],
    }
