"""source: ADR-0625"""

from __future__ import annotations

from pathlib import Path

from mcp_server.infrastructure.project_wiki import contained_file, load_manifest
from mcp_server.infrastructure.wiki_decision_index import decision_index


def mirror_bytes(identifier: str, source: str, content: bytes) -> bytes:
    banner = (
        f"<!-- Generated by Cortex wiki_reindex from wiki/{source}; "
        f"{identifier}. Read-only mirror: edit the canonical wiki page. -->\n\n"
    )
    return banner.encode("utf-8") + content


def expected_mirror(project_root: Path) -> dict[str, bytes]:
    root = project_root.resolve()
    manifest = load_manifest(root)
    indexed = decision_index(root / "wiki")
    if set(indexed) != set(manifest["pages"]):
        raise ValueError("project wiki manifest and canonical decision IDs differ")
    expected: dict[str, bytes] = {}
    for identifier, entry in sorted(manifest["pages"].items()):
        if not isinstance(entry, dict) or entry.get("path") != indexed[identifier]:
            raise ValueError(f"manifest source does not match {identifier}")
        name = entry.get("mirror")
        if (
            not isinstance(name, str)
            or Path(name).name != name
            or not name.endswith(".md")
        ):
            raise ValueError(f"invalid mirror filename for {identifier}")
        if name in expected:
            raise ValueError(f"duplicate mirror filename: {name}")
        source = contained_file(root / "wiki", entry["path"])
        contained_file(root, "docs/adr/" + name)
        expected[name] = mirror_bytes(identifier, entry["path"], source.read_bytes())
    return expected


def _extra_files(project_root: Path, expected: dict[str, bytes]) -> list[str]:
    folder = contained_file(project_root.resolve(), "docs/adr")
    if not folder.exists():
        return []
    return sorted(
        str(p.relative_to(folder))
        for p in folder.rglob("*")
        if (p.is_file() or p.is_symlink())
        and str(p.relative_to(folder)) not in expected
    )


def check_mirror(project_root: Path) -> list[str]:
    try:
        expected = expected_mirror(project_root)
        errors = [
            f"unexpected mirror file: {name}"
            for name in _extra_files(project_root, expected)
        ]
        for name, content in expected.items():
            target = contained_file(project_root.resolve(), "docs/adr/" + name)
            if not target.is_file():
                errors.append(f"missing decision mirror: {name}")
            elif target.read_bytes() != content:
                errors.append(f"stale or edited decision mirror: {name}")
        return errors
    except (OSError, ValueError, KeyError, TypeError) as exc:
        return [f"invalid project wiki mirror: {exc}"]


def generate_mirror(project_root: Path) -> dict[str, object]:
    expected = expected_mirror(project_root)
    extra = _extra_files(project_root, expected)
    if extra:
        raise ValueError(f"unmanaged mirror files; remove explicitly: {extra}")
    changed = []
    for name, content in expected.items():
        target = contained_file(project_root.resolve(), "docs/adr/" + name)
        if target.exists() and target.read_bytes() == content:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = contained_file(project_root.resolve(), "docs/adr/" + name + ".tmp")
        temporary.write_bytes(content)
        temporary.replace(target)
        changed.append(name)
    return {"mirror_pages": len(expected), "mirror_changed": changed}
