"""Handler: wiki_reindex — regenerate the wiki table of contents.

source: ADR-0468"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from mcp_server.shared.wiki_layout import PAGE_KINDS, index_path
from mcp_server.core.wiki_redirect import is_redirect, parse_frontmatter
from mcp_server.handlers._tool_meta import IDEMPOTENT_WRITE
from mcp_server.infrastructure.config import WIKI_ROOT
from mcp_server.infrastructure.wiki_decision_index import write_decision_index
from mcp_server.handlers import project_wiki
from mcp_server.infrastructure.wiki_pages_listing import list_pages
from mcp_server.infrastructure.wiki_store import read_page, write_page

_BANNER = (
    "<!-- Generated by Cortex wiki_reindex — the authored pages are the "
    "source of truth. -->"
)

schema = {
    "title": "Wiki — reindex",
    "annotations": IDEMPOTENT_WRITE,
    "description": (
        # source: ADR-0468
        "Regenerate the wiki table of contents at "
        "<wiki_root>/.generated/INDEX.md by enumerating every authored "
        "page and grouping it by kind (adr, specs, guides, reference, "
        "conventions, lessons, notes, journal, files). Redirect stubs are "
        "excluded; auto-generated pages (``provenance: auto-generated``) "
        "are surfaced in a separate ``Auto-generated reference`` section "
        "after the human-authored content. Output is deterministic — "
        "sorted by kind then path so unchanged wikis yield byte-identical "
        "INDEX files. Authored pages are never touched. INDEX.md and the "
        "exact decision map are refreshed; project mode also updates "
        "docs/adr. Use this after bulk wiki edits, imports, or "
        "`wiki_compile` runs. Distinct from `wiki_list` (returns the "
        "listing in the response, no file write) and from "
        "`wiki_consolidate` (heat decay / staleness, not ToC rebuild). An "
        "explicit project_root isolates project publication. Latency "
        "<500ms on a 9000-page wiki. Returns {path, total_pages, by_kind, "
        "auto_generated_by_kind, redirect_count, root}."
    ),
    "inputSchema": {
        "type": "object",
        "required": [],
        "properties": {
            "project_root": {
                "type": "string",
                "description": (
                    "Repository with wiki/manifest.json; filesystem-only project mode."
                ),
            },
        },
        "additionalProperties": False,
    },
}


def _render_index(
    grouped: dict[str, list[str]],
    auto_grouped: dict[str, list[str]],
) -> str:
    """Render INDEX.md with human-authored content first, auto-gen second.

    source: ADR-0468"""
    lines: list[str] = [_BANNER, "", "# Wiki Index", ""]
    total_human = sum(len(v) for v in grouped.values())
    total_auto = sum(len(v) for v in auto_grouped.values())
    lines.append(
        f"**{total_human} human-authored pages, "
        f"{total_auto} auto-generated reference pages.**"
    )
    lines.append("")

    lines.append("## Human-authored")
    lines.append("")
    for kind in PAGE_KINDS:
        pages = grouped.get(kind, [])
        lines.append(f"### {kind} ({len(pages)})")
        lines.append("")
        if not pages:
            lines.append("_No pages yet._")
            lines.append("")
            continue
        for rel in pages:
            name = rel.rsplit("/", 1)[-1]
            lines.append(f"- [{name}](../{rel})")
        lines.append("")

    if total_auto > 0:
        lines.append("## Auto-generated reference")
        lines.append("")
        lines.append(
            "_Produced by ``codebase_analyze`` and similar tooling. "
            "Lookup-shaped, not curated narrative._"
        )
        lines.append("")
        for kind in PAGE_KINDS:
            pages = auto_grouped.get(kind, [])
            if not pages:
                continue
            lines.append(f"### {kind} ({len(pages)})")
            lines.append("")
            for rel in pages:
                name = rel.rsplit("/", 1)[-1]
                lines.append(f"- [{name}](../{rel})")
            lines.append("")
    return "\n".join(lines)


def _classify_page(rel_path: str, root: Path | str = WIKI_ROOT) -> tuple[bool, bool]:
    """Read frontmatter once; return (is_redirect_stub, is_auto_generated)."""
    try:
        content = read_page(root, rel_path)
    except (ValueError, OSError):
        return False, False
    if content is None:
        return False, False
    fm = parse_frontmatter(content)
    redirect_flag = is_redirect(fm)
    raw_prov = fm.get("provenance", "")
    auto_gen_flag = (
        isinstance(raw_prov, str) and raw_prov.strip().lower() == "auto-generated"
    )
    return redirect_flag, auto_gen_flag


def _classify_kind(root: Path | str, kind: str) -> tuple[list[str], list[str], int]:
    try:
        pages = list_pages(root, kind=kind)
    except (ValueError, OSError):
        return [], [], 0
    live: list[str] = []
    auto: list[str] = []
    redirects = 0
    for relative in pages:
        redirect, generated = _classify_page(relative, root)
        if redirect:
            redirects += 1
        elif generated:
            auto.append(relative)
        else:
            live.append(relative)
    return live, auto, redirects


def reindex(root: Path | str) -> dict[str, Any]:
    """. split human / auto-gen / redirects.

        Redirects: excluded entirely from INDEX.md (they're navigational aids
        for inbound links, not content to advertise). Counted in the summary.

        Auto-generated pages: surfaced in their own section after the
        human-authored content so they don't drown the main listing.

    source: ADR-0468"""
    grouped: dict[str, list[str]] = {}
    auto_grouped: dict[str, list[str]] = {}
    redirects_by_kind: dict[str, int] = {}
    auto_by_kind: dict[str, int] = {}

    for kind in PAGE_KINDS:
        live, auto, redirects = _classify_kind(root, kind)
        grouped[kind] = live
        auto_grouped[kind] = auto
        redirects_by_kind[kind] = redirects
        auto_by_kind[kind] = len(auto)

    write_decision_index(root)
    content = _render_index(grouped, auto_grouped)
    write_page(root, str(index_path()), content, mode="replace")

    return {
        "path": str(index_path()),
        "total_pages": sum(len(v) for v in grouped.values())
        + sum(len(v) for v in auto_grouped.values()),
        "by_kind": {k: len(v) for k, v in grouped.items()},
        "auto_generated_by_kind": auto_by_kind,
        "redirects_by_kind": redirects_by_kind,
        "redirect_count": sum(redirects_by_kind.values()),
        "auto_generated_count": sum(auto_by_kind.values()),
        "root": str(root),
    }


async def handler(args: dict[str, Any] | None = None) -> dict[str, Any]:
    args = args or {}
    try:
        if args.get("project_root") is not None:
            return project_wiki.reindex_project(args["project_root"], reindex)
        return reindex(WIKI_ROOT)
    except (ValueError, OSError) as exc:
        return {"error": f"wiki reindex failed: {exc}"}
