"""Handler: wiki_reindex — regenerate the wiki table of contents.

The *only* file this handler writes is ``<root>/.generated/INDEX.md``.
Authored pages are enumerated via ``list_pages`` and grouped by kind.
Deterministic output: sorted by kind then path so unchanged wikis yield
byte-identical INDEX files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from mcp_server.core.wiki_layout import PAGE_KINDS, index_path
from mcp_server.infrastructure.config import WIKI_ROOT
from mcp_server.infrastructure.file_io import ensure_dir
from mcp_server.infrastructure.wiki_store import list_pages

_BANNER = (
    "<!-- Generated by Cortex wiki_reindex — the authored pages are the "
    "source of truth. -->"
)

schema = {
    "description": (
        "Regenerate the wiki table of contents at .generated/INDEX.md. "
        "Authored pages are never touched."
    ),
    "inputSchema": {"type": "object", "properties": {}},
}


def _render_index(grouped: dict[str, list[str]]) -> str:
    lines: list[str] = [_BANNER, "", "# Wiki Index", ""]
    total = sum(len(v) for v in grouped.values())
    lines.append(f"**{total} authored pages across {len(PAGE_KINDS)} kinds.**")
    lines.append("")
    for kind in PAGE_KINDS:
        pages = grouped.get(kind, [])
        lines.append(f"## {kind} ({len(pages)})")
        lines.append("")
        if not pages:
            lines.append("_No pages yet._")
            lines.append("")
            continue
        for rel in pages:
            name = rel.rsplit("/", 1)[-1]
            lines.append(f"- [{name}](../{rel})")
        lines.append("")
    return "\n".join(lines)


async def handler(args: dict[str, Any] | None = None) -> dict[str, Any]:
    grouped: dict[str, list[str]] = {}
    for kind in PAGE_KINDS:
        try:
            grouped[kind] = list_pages(WIKI_ROOT, kind=kind)
        except (ValueError, OSError):
            grouped[kind] = []

    content = _render_index(grouped)
    target = Path(WIKI_ROOT) / str(index_path())
    ensure_dir(target.parent)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(target)

    return {
        "path": str(index_path()),
        "total_pages": sum(len(v) for v in grouped.values()),
        "by_kind": {k: len(v) for k, v in grouped.items()},
        "root": str(WIKI_ROOT),
    }
