"""Handler: wiki_reindex — regenerate the wiki table of contents.

The *only* file this handler writes is ``<root>/.generated/INDEX.md``.
Authored pages are enumerated via ``list_pages`` and grouped by kind.
Deterministic output: sorted by kind then path so unchanged wikis yield
byte-identical INDEX files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from mcp_server.core.wiki_layout import PAGE_KINDS, index_path
from mcp_server.core.wiki_redirect import is_redirect, parse_frontmatter
from mcp_server.handlers._tool_meta import IDEMPOTENT_WRITE
from mcp_server.infrastructure.config import WIKI_ROOT
from mcp_server.infrastructure.file_io import ensure_dir
from mcp_server.infrastructure.wiki_store import list_pages, read_page

_BANNER = (
    "<!-- Generated by Cortex wiki_reindex — the authored pages are the "
    "source of truth. -->"
)

schema = {
    "title": "Wiki — reindex",
    "annotations": IDEMPOTENT_WRITE,
    "description": (
        "Regenerate the wiki table of contents at "
        "<wiki_root>/.generated/INDEX.md by enumerating every authored page "
        "and grouping it by kind (adr, specs, guides, reference, "
        "conventions, lessons, notes, journal, files). Output is "
        "deterministic — sorted by kind then path so unchanged wikis yield "
        "byte-identical INDEX files. Authored pages are never touched; the "
        "only file written is INDEX.md, atomically via tmp+rename. Use this "
        "after bulk wiki edits, imports, or `wiki_compile` runs. Distinct "
        "from `wiki_list` (returns the listing in the response, no file "
        "write) and from `wiki_consolidate` (heat decay / staleness, not ToC "
        "rebuild). Takes no arguments. Latency <100ms even for thousands of "
        "pages. Returns {path, total_pages, by_kind: {kind: count}, root}."
    ),
    "inputSchema": {
        "type": "object",
        "required": [],
        "properties": {},
        "additionalProperties": False,
    },
}


def _render_index(grouped: dict[str, list[str]]) -> str:
    lines: list[str] = [_BANNER, "", "# Wiki Index", ""]
    total = sum(len(v) for v in grouped.values())
    lines.append(f"**{total} authored pages across {len(PAGE_KINDS)} kinds.**")
    lines.append("")
    for kind in PAGE_KINDS:
        pages = grouped.get(kind, [])
        lines.append(f"## {kind} ({len(pages)})")
        lines.append("")
        if not pages:
            lines.append("_No pages yet._")
            lines.append("")
            continue
        for rel in pages:
            name = rel.rsplit("/", 1)[-1]
            lines.append(f"- [{name}](../{rel})")
        lines.append("")
    return "\n".join(lines)


def _is_redirect_page(rel_path: str) -> bool:
    """True iff the page declares a redirect (read frontmatter from disk)."""
    try:
        content = read_page(WIKI_ROOT, rel_path)
    except (ValueError, OSError):
        return False
    if content is None:
        return False
    return is_redirect(parse_frontmatter(content))


async def handler(args: dict[str, Any] | None = None) -> dict[str, Any]:
    """Phase 3.2 of ADR-2244: redirect stubs are excluded from the index.

    The reader-facing INDEX.md should only list live pages — a stub at
    an old path is a navigation aid for inbound links, not content to
    advertise. The summary still reports the count of stubs so callers
    have visibility.
    """
    grouped: dict[str, list[str]] = {}
    redirects_by_kind: dict[str, int] = {}
    for kind in PAGE_KINDS:
        try:
            all_pages = list_pages(WIKI_ROOT, kind=kind)
        except (ValueError, OSError):
            grouped[kind] = []
            redirects_by_kind[kind] = 0
            continue
        live: list[str] = []
        n_redirect = 0
        for rel in all_pages:
            if _is_redirect_page(rel):
                n_redirect += 1
            else:
                live.append(rel)
        grouped[kind] = live
        redirects_by_kind[kind] = n_redirect

    content = _render_index(grouped)
    target = Path(WIKI_ROOT) / str(index_path())
    ensure_dir(target.parent)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(target)

    return {
        "path": str(index_path()),
        "total_pages": sum(len(v) for v in grouped.values()),
        "by_kind": {k: len(v) for k, v in grouped.items()},
        "redirects_by_kind": redirects_by_kind,
        "redirect_count": sum(redirects_by_kind.values()),
        "root": str(WIKI_ROOT),
    }
