"""scripts/setup.py's dependency install must resolve from the generated,
hash-pinned constraint file, not a hand-written package list — issue #538.

Prior state: ``install_deps()`` built its own ``packages = ["mcp>=2.0.0",
...]`` list of loose version ranges and passed it straight to ``pip
install --target``. No pin, no hash, no reference to uv.lock. That is
the SQLite-backend path on every OS and the PostgreSQL path on Windows —
the default zero-config install. ``requirements/setup.txt`` (exported
from uv.lock by scripts/generate_pip_constraints.py) exists precisely to
avoid this drift and is what scripts/setup.sh already installs.

This test inspects the actual argv ``install_deps()`` passes to pip (via
the module's ``run`` hook, mocked so no network call happens) and asserts:
  - the source is ``-r requirements/setup.txt``, not a Python list literal
  - ``--no-deps`` is present (ADR-1059: pip must not re-derive the graph
    uv's ``[tool.uv] override-dependencies`` already resolved)
  - ``--require-hashes`` is present
  - ``--upgrade`` is absent (ADR-1059: this directory may be on a live
    MCP server's sys.path; skip-if-present is safe under concurrency,
    replace-in-place is not)
  - no hand-written ``name>=version`` requirement specifier reaches pip

source: ADR-1059"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[2]
SETUP_MODULE_PATH = REPO_ROOT / "scripts" / "setup.py"
LOCK_EXPORT_PATH = REPO_ROOT / "requirements" / "setup.txt"

# A hand-written loose requirement specifier: NAME>=X.Y.Z (optionally with
# an extras marker like psycopg[binary]). Matches what the old hand list
# used ("mcp>=2.0.0", "psycopg[binary]>=3.1", ...); must never appear in
# the argv install_deps() hands to pip.
_LOOSE_SPEC = re.compile(r"^[A-Za-z0-9_.-]+(\[[a-z]+\])?>=[0-9]")


def _load_setup_module():
    """Import scripts/setup.py fresh, dotted to match mutmut's path-derived
    trampoline name (issue #262) — see test_setup_py_backend_skip.py.
    """
    spec = importlib.util.spec_from_file_location("scripts.setup", SETUP_MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_install_deps_resolves_from_the_generated_constraint_file():
    mod = _load_setup_module()
    fake_run = mock.Mock(return_value=mock.Mock(returncode=0, stderr=""))
    with mock.patch.object(mod, "run", fake_run):
        mod.install_deps()

    fake_run.assert_called_once()
    (argv,), _kwargs = fake_run.call_args

    # The source is the generated constraint file, not an inline list.
    assert "-r" in argv, argv
    source = argv[argv.index("-r") + 1]
    assert Path(source) == LOCK_EXPORT_PATH, (
        f"install_deps() reads {source!r}, expected the generated "
        f"{LOCK_EXPORT_PATH} (scripts/pip_constraint_sets.py, entry "
        f'"setup.txt")'
    )

    assert "--no-deps" in argv, (
        "install_deps() must pass --no-deps: the constraint file is the "
        "fully uv-resolved closure and pip re-deriving it aborts with "
        "ResolutionImpossible on the mpmath override (ADR-1059)"
    )
    assert "--require-hashes" in argv, (
        "install_deps() must pass --require-hashes: every line in the "
        "generated constraint file is hash-pinned"
    )
    assert "--upgrade" not in argv, (
        "install_deps() must NOT pass --upgrade: DEPS_DIR may be on a "
        "live MCP server's sys.path (ADR-0749) and pip's delete-then-"
        "rewrite under --upgrade is not safe there (ADR-1059)"
    )

    # No hand-written loose specifier reaches pip.
    hand_written = [arg for arg in argv if _LOOSE_SPEC.match(arg)]
    assert not hand_written, (
        f"install_deps() still passes hand-written version ranges to pip: "
        f"{hand_written} — these must come only from {LOCK_EXPORT_PATH}"
    )


def test_generated_constraint_file_exists_and_is_hash_pinned():
    """Guard the fixture itself: the file the test above points at must be
    the real generated, hashed export, not an empty/missing placeholder."""
    assert LOCK_EXPORT_PATH.is_file()
    text = LOCK_EXPORT_PATH.read_text(encoding="utf-8")
    assert "GENERATED by scripts/generate_pip_constraints.py" in text
    assert "--hash=sha256:" in text
