"""Tests for scripts/pip_constraint_sets.py — the table's OWN logic.

`test_generate_pip_constraints.py` asserts the committed requirements/*.txt
artifacts and `test_typecheck_env_parity.py` reads `SETS` fields to
cross-check CONTRIBUTING.md/CI; neither exercises `constraint_path`,
`constraint_command`, or `constraint_header_lines` directly; every real call
goes through `compose()`/`render()`, which the other two test files either
mock or short-circuit before reaching. So this module's logic carried zero
mutation coverage twice over: once because it used to live on a
`@dataclass`-decorated class (mutmut excludes decorated-class bodies
outright, since copying one for the trampoline setup can re-run the
decorator's side effects), and again because nothing calls the extracted
functions for real (issue #262).
"""

from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Dotted to match the path-derived name mutmut keys mutant trampolines on
# ("scripts.pip_constraint_sets.*") — a bare module name makes every mutant
# look unreached to a scoped mutation run (issue #262).
_spec = importlib.util.spec_from_file_location(
    "scripts.pip_constraint_sets", REPO / "scripts" / "pip_constraint_sets.py"
)
pip_constraint_sets = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = pip_constraint_sets
_spec.loader.exec_module(pip_constraint_sets)


def _set(**overrides: object):
    """A `ConstraintSet` with every field defaulted except what's overridden."""
    fields: dict[str, object] = {
        "filename": "example.txt",
        "consumers": ("a consumer",),
        "extras": (),
        "groups": (),
        "only_groups": (),
        "note": "",
    }
    fields.update(overrides)
    return pip_constraint_sets.ConstraintSet(**fields)


class ConstraintPathTests(unittest.TestCase):
    def test_path_is_requirements_dir_over_filename(self) -> None:
        constraint_set = _set(filename="thing.txt")
        self.assertEqual(
            pip_constraint_sets.constraint_path(constraint_set),
            pip_constraint_sets.REQUIREMENTS_DIR / "thing.txt",
        )


class ConstraintCommandTests(unittest.TestCase):
    def test_base_command_is_a_locked_stdout_export(self) -> None:
        command = pip_constraint_sets.constraint_command(_set())
        self.assertEqual(
            command,
            [
                "uv",
                "export",
                "--locked",
                "--no-emit-project",
                "--no-default-groups",
                "--format",
                "requirements.txt",
            ],
        )

    def test_extras_append_a_flag_pair_each(self) -> None:
        command = pip_constraint_sets.constraint_command(_set(extras=("dev", "sqlite")))
        self.assertEqual(command[-4:], ["--extra", "dev", "--extra", "sqlite"])

    def test_groups_append_a_flag_pair_each(self) -> None:
        command = pip_constraint_sets.constraint_command(_set(groups=("container",)))
        self.assertEqual(command[-2:], ["--group", "container"])

    def test_only_groups_append_a_flag_pair_each(self) -> None:
        command = pip_constraint_sets.constraint_command(
            _set(only_groups=("lint", "typecheck"))
        )
        self.assertEqual(
            command[-4:], ["--only-group", "lint", "--only-group", "typecheck"]
        )

    def test_extras_groups_and_only_groups_add_to_the_base_command(self) -> None:
        """Regression guard for `cmd += [...]` degrading to `cmd = [...]`:
        each accumulator must ADD to the base command, never replace it."""
        command = pip_constraint_sets.constraint_command(
            _set(extras=("dev",), groups=("container",), only_groups=("lint",))
        )
        self.assertEqual(
            command,
            [
                "uv",
                "export",
                "--locked",
                "--no-emit-project",
                "--no-default-groups",
                "--format",
                "requirements.txt",
                "--extra",
                "dev",
                "--group",
                "container",
                "--only-group",
                "lint",
            ],
        )


class ConstraintHeaderLinesTests(unittest.TestCase):
    def test_banner_states_generation_provenance(self) -> None:
        """Exact equality, not `assertIn`: the two bare "#" separator lines
        carry no distinguishing text of their own, so only a full-sequence
        check pins their content and position."""
        lines = pip_constraint_sets.constraint_header_lines(_set())
        self.assertEqual(
            lines,
            [
                "#" * 74,
                "# GENERATED by scripts/generate_pip_constraints.py"
                " — do not hand-edit.",
                "#",
                "# Source of truth: uv.lock. Regenerate with",
                "#     python3 scripts/generate_pip_constraints.py",
                "# and commit the result; CI re-runs it with --check and"
                " fails on drift.",
                "#",
                "# Read by:",
                "#   a consumer",
                "#" * 74,
            ],
        )

    def test_every_consumer_is_listed(self) -> None:
        lines = pip_constraint_sets.constraint_header_lines(_set(consumers=("a", "b")))
        self.assertIn("#   a", lines)
        self.assertIn("#   b", lines)

    def test_a_note_is_wrapped_after_a_blank_comment_line(self) -> None:
        lines = pip_constraint_sets.constraint_header_lines(_set(note="first\nsecond"))
        self.assertIn("# first", lines)
        self.assertIn("# second", lines)
        first_idx = lines.index("# first")
        self.assertEqual(lines[first_idx - 1], "#")

    def test_an_empty_note_adds_nothing(self) -> None:
        with_note = pip_constraint_sets.constraint_header_lines(_set(note="x"))
        without_note = pip_constraint_sets.constraint_header_lines(_set(note=""))
        # The note contributes exactly a blank "#" plus one "# <line>" per line.
        self.assertEqual(len(without_note), len(with_note) - 2)


if __name__ == "__main__":
    unittest.main()
