"""Wiki projection — pure rendering of memory state to Markdown.

Slice 1: builds the global INDEX.md and one per-domain INDEX.md page from
a deterministic snapshot. No I/O. No LLM. Same input → byte-identical
output (enables golden tests and mtime no-op writes).

This module is a *renderer*, not a memory mechanism. It cites no paper
because it adds no epistemic content — PostgreSQL remains the single
source of truth. The wiki is a read-only projection for inspectability
and adoption (browsable Markdown, Mermaid charts in Claude Code CLI).

See tasks/refactoring-plan.md and CLAUDE.md for the broader plan. Later
slices will add schema pages, causal chain pages, and Mermaid blocks.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import PurePosixPath

from mcp_server.core.wiki_layout import (
    chain_page_path,
    domain_index_path,
    global_index_path,
    schema_page_path,
)
from mcp_server.core.wiki_mermaid import (
    causal_chain_graph,
    schema_entity_wheel,
    schema_overlap_graph,
)

_BANNER = (
    "<!-- Generated by Cortex wiki_sync — edits will be overwritten. "
    "Source of truth is PostgreSQL; this file is a read-only projection. -->"
)


@dataclass(frozen=True)
class DomainSummary:
    """Minimal per-domain facts needed for slice 1 INDEX rendering."""

    id: str
    label: str
    session_count: int = 0
    confidence: float = 0.0
    last_active: str | None = None
    top_categories: tuple[str, ...] = ()
    dominant_mode: str | None = None


@dataclass(frozen=True)
class SchemaInfo:
    """Per-schema facts for rendering. Sourced from PG `schemas` rows."""

    schema_id: str
    domain_id: str
    label: str
    entity_signature: dict[str, float] = field(default_factory=dict)
    tag_signature: dict[str, float] = field(default_factory=dict)
    formation_count: int = 0
    assimilation_count: int = 0
    violation_count: int = 0


@dataclass(frozen=True)
class CausalChain:
    """Memory-seeded causal chain rendered from entity-graph BFS.

    Each chain corresponds to one hot memory in a domain; edges are
    pre-resolved (BFS done in the handler) so core stays I/O-free.
    """

    chain_id: str
    domain_id: str
    seed_memory_id: int
    seed_label: str
    seed_heat: float = 0.0
    edges: tuple[tuple[str, str, str], ...] = ()  # (src, rel_type, tgt)


@dataclass(frozen=True)
class WikiSnapshot:
    """Deterministic input bundle for the projection.

    Slices add fields here (schemas, chains, cascade stats, heat buckets);
    they never reach into stores from inside core.
    """

    domains: tuple[DomainSummary, ...] = ()
    global_style: str | None = None
    schemas: tuple[SchemaInfo, ...] = ()
    chains: tuple[CausalChain, ...] = ()


@dataclass(frozen=True)
class WikiPage:
    """A single rendered page. `path` is relative to the wiki root."""

    path: PurePosixPath
    markdown: str


def _sorted_domains(domains: tuple[DomainSummary, ...]) -> list[DomainSummary]:
    """Sort by session_count desc then id asc — stable across runs."""
    return sorted(domains, key=lambda d: (-d.session_count, d.id))


def _schemas_for(domain_id: str, schemas: tuple[SchemaInfo, ...]) -> list[SchemaInfo]:
    """Per-domain schemas, sorted by formation_count desc then schema_id."""
    matched = [s for s in schemas if s.domain_id == domain_id]
    return sorted(matched, key=lambda s: (-s.formation_count, s.schema_id))


def _chains_for(domain_id: str, chains: tuple[CausalChain, ...]) -> list[CausalChain]:
    """Per-domain chains, sorted by seed_heat desc then chain_id."""
    matched = [c for c in chains if c.domain_id == domain_id]
    return sorted(matched, key=lambda c: (-c.seed_heat, c.chain_id))


def _render_global_index(snapshot: WikiSnapshot) -> str:
    lines: list[str] = [_BANNER, "", "# Cortex Memory Wiki", ""]
    if snapshot.global_style:
        lines += [f"**Global cognitive style:** {snapshot.global_style}", ""]
    lines += [f"**Domains tracked:** {len(snapshot.domains)}", ""]
    if not snapshot.domains:
        lines += ["_No domains yet. Use Cortex for a few sessions to populate._", ""]
        return "\n".join(lines)
    lines += ["## Domains", ""]
    lines += ["| Domain | Sessions | Confidence | Last active |"]
    lines += ["|---|---:|---:|---|"]
    for d in _sorted_domains(snapshot.domains):
        link = f"[{d.label}]({d.id}/INDEX.md)"
        last = d.last_active or "—"
        lines += [
            f"| {link} | {d.session_count} | {d.confidence:.2f} | {last} |"
        ]
    lines += [""]
    return "\n".join(lines)


def _render_domain_index(
    domain: DomainSummary,
    schemas: list[SchemaInfo],
    chains: list[CausalChain],
) -> str:
    lines: list[str] = [_BANNER, "", f"# {domain.label}", ""]
    lines += [
        f"- **ID:** `{domain.id}`",
        f"- **Sessions:** {domain.session_count}",
        f"- **Confidence:** {domain.confidence:.2f}",
        f"- **Last active:** {domain.last_active or '—'}",
    ]
    if domain.dominant_mode:
        lines += [f"- **Dominant mode:** {domain.dominant_mode}"]
    lines += [""]
    if domain.top_categories:
        lines += ["## Top categories", ""]
        for cat in domain.top_categories:
            lines += [f"- {cat}"]
        lines += [""]
    lines += ["## Schemas", ""]
    if schemas:
        lines += [f"_{len(schemas)} schemas in this domain._", ""]
        for s in schemas:
            link = f"schemas/{_filename_for_schema(s.schema_id)}"
            lines += [
                f"- [{s.label or s.schema_id}]({link}) "
                f"— {s.formation_count} formations, "
                f"{s.assimilation_count} assimilations"
            ]
        lines += ["", "### Schema overlap graph", ""]
        overlap_input = [
            (s.schema_id, s.label or s.schema_id, s.entity_signature) for s in schemas
        ]
        lines += [schema_overlap_graph(overlap_input), ""]
    else:
        lines += ["_No schemas formed yet for this domain._", ""]
    lines += ["## Causal chains", ""]
    if chains:
        lines += [f"_{len(chains)} chains seeded from hot memories._", ""]
        for c in chains:
            link = f"chains/{_filename_for_schema(c.chain_id)}"
            lines += [
                f"- [{c.seed_label}]({link}) "
                f"— heat {c.seed_heat:.2f}, {len(c.edges)} edges"
            ]
        lines += [""]
    else:
        lines += ["_No causal chains for this domain yet._", ""]
    return "\n".join(lines)


def _filename_for_schema(schema_id: str) -> str:
    """Mirror wiki_layout.schema_page_path's leaf name."""
    from mcp_server.core.wiki_layout import slugify

    return f"{slugify(schema_id)}.md"


def _render_schema_page(domain: DomainSummary, schema: SchemaInfo) -> str:
    lines: list[str] = [_BANNER, "", f"# {schema.label or schema.schema_id}", ""]
    lines += [
        f"- **Schema ID:** `{schema.schema_id}`",
        f"- **Domain:** [{domain.label}](../INDEX.md)",
        f"- **Formations:** {schema.formation_count}",
        f"- **Assimilations:** {schema.assimilation_count}",
        f"- **Violations:** {schema.violation_count}",
        "",
    ]
    if schema.entity_signature:
        lines += ["## Top entities", ""]
        top = sorted(
            schema.entity_signature.items(),
            key=lambda kv: (-kv[1], kv[0]),
        )[:10]
        lines += ["| Entity | Weight |", "|---|---:|"]
        for name, weight in top:
            lines += [f"| {name} | {weight:.2f} |"]
        lines += [""]
    if schema.tag_signature:
        tags = sorted(
            schema.tag_signature.items(),
            key=lambda kv: (-kv[1], kv[0]),
        )[:10]
        lines += [
            "## Top tags",
            "",
            ", ".join(f"`{t}` ({w:.2f})" for t, w in tags),
            "",
        ]
    lines += [
        "## Entity wheel",
        "",
        schema_entity_wheel(schema.label or schema.schema_id, schema.entity_signature),
        "",
    ]
    return "\n".join(lines)


def _render_chain_page(domain: DomainSummary, chain: CausalChain) -> str:
    lines: list[str] = [_BANNER, "", f"# Chain: {chain.seed_label}", ""]
    lines += [
        f"- **Chain ID:** `{chain.chain_id}`",
        f"- **Domain:** [{domain.label}](../INDEX.md)",
        f"- **Seed memory:** `#{chain.seed_memory_id}` (heat {chain.seed_heat:.2f})",
        f"- **Edges:** {len(chain.edges)}",
        "",
        "## Graph",
        "",
        causal_chain_graph(list(chain.edges)),
        "",
    ]
    if chain.edges:
        lines += ["## Edge list", "", "| Source | Relation | Target |", "|---|---|---|"]
        for src, rel, tgt in sorted(chain.edges, key=lambda e: (e[0], e[2])):
            lines += [f"| {src} | {rel} | {tgt} |"]
        lines += [""]
    return "\n".join(lines)


def build_pages(snapshot: WikiSnapshot) -> list[WikiPage]:
    """Render the entire wiki for a snapshot. Pure function."""
    pages: list[WikiPage] = [
        WikiPage(path=global_index_path(), markdown=_render_global_index(snapshot))
    ]
    for domain in _sorted_domains(snapshot.domains):
        domain_schemas = _schemas_for(domain.id, snapshot.schemas)
        domain_chains = _chains_for(domain.id, snapshot.chains)
        pages.append(
            WikiPage(
                path=domain_index_path(domain.id),
                markdown=_render_domain_index(domain, domain_schemas, domain_chains),
            )
        )
        for schema in domain_schemas:
            pages.append(
                WikiPage(
                    path=schema_page_path(domain.id, schema.schema_id),
                    markdown=_render_schema_page(domain, schema),
                )
            )
        for chain in domain_chains:
            pages.append(
                WikiPage(
                    path=chain_page_path(domain.id, chain.chain_id),
                    markdown=_render_chain_page(domain, chain),
                )
            )
    return pages
