"""Baseline load/save/diff for the craftsmanship gate.

This module supplies the parsing both paths share
(``parse_baseline_json``); the git plumbing lives in
``check_craftsmanship.py``, which already owns ``_run_git``.

source: ADR-0720"""

from __future__ import annotations

import datetime as _dt
import json
import sys
from collections import Counter
from pathlib import Path

_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
from craftsmanship_rules import Violation  # noqa: E402


def parse_baseline_json(text: str) -> set[Violation]:
    """Parse a baseline JSON document's ``violations`` array.

    Shared by ``load_baseline`` (working tree) and
    ``check_craftsmanship.load_baseline_from_ref`` (``git show`` output) —
    the two loaders differ only in how they obtain ``text``, never in how
    they interpret it.
    """
    data = json.loads(text)
    return {
        Violation(entry["file"], entry["kind"], entry["detail"])
        for entry in data.get("violations", [])
    }


def load_baseline(path: Path) -> set[Violation]:
    """Return the baselined violations, or an empty set if none exists yet."""
    if not path.exists():
        return set()
    return parse_baseline_json(path.read_text(encoding="utf-8"))


def save_baseline(path: Path, violations: set[Violation]) -> None:
    """Write ``violations`` as the new baseline, sorted for a stable diff."""
    entries = sorted(
        ({"file": v.file, "kind": v.kind, "detail": v.detail} for v in violations),
        key=lambda entry: (entry["file"], entry["kind"], entry["detail"]),
    )
    payload = {
        "$comment": (
            "Generated by `python scripts/check_craftsmanship.py --write-baseline`. "
            "Do NOT add an entry by hand to silence a new violation — that is "
            "gaming the ratchet, not maintaining it "
            "(docs/agent-guidance.md § Code Style). "
            "Regenerate only after confirming every new entry is pre-existing "
            "debt, not something this PR just introduced. Every entry removed "
            "here must correspond to a violation actually fixed in the code."
        ),
        "generated": _dt.datetime.now(tz=_dt.timezone.utc).date().isoformat(),
        "violations": entries,
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def new_violations(
    current: set[Violation], baseline: set[Violation]
) -> list[Violation]:
    """Violations present now but absent from the baseline — these block."""
    return sorted(current - baseline, key=lambda v: (v.file, v.kind, v.detail))


def stale_entries(
    baseline: set[Violation], rescanned: dict[str, set[Violation]]
) -> list[Violation]:
    """Baseline entries whose violation no longer exists in the current code.

    source: ADR-0720"""
    stale = [
        entry for entry in baseline if entry not in rescanned.get(entry.file, set())
    ]
    return sorted(stale, key=lambda v: (v.file, v.kind, v.detail))


def added_entries(
    working_baseline: set[Violation], base_baseline: set[Violation]
) -> list[Violation]:
    """Entries present in this PR's baseline file but absent from the base
        ref's — the ratchet-file check.

    source: ADR-0720"""
    return sorted(
        working_baseline - base_baseline, key=lambda v: (v.file, v.kind, v.detail)
    )


def falsified_removals(
    base_baseline: set[Violation],
    working_baseline: set[Violation],
    rescanned: dict[str, set[Violation]],
) -> list[Violation]:
    """The mirror image of ``added_entries``, flagged in review: closing
        "add a violation, then run --write-baseline in the same tree" without
        also closing "delete the JSON line by hand, leave the violation in
        place" left the ratchet open on the removal side — any of the ~1400
        grandfathered entries could be hand-deleted from
        ``.craftsmanship-baseline.json`` for free, since neither
        ``added_entries`` (only looks at additions) nor ``new_violations``
        (only rescans this PR's diffed files, not every baselined file) would
        ever see it.

    source: ADR-0720"""
    removed = base_baseline - working_baseline
    falsified = [v for v in removed if v in rescanned.get(v.file, set())]
    return sorted(falsified, key=lambda v: (v.file, v.kind, v.detail))


def count_by_kind(violations: set[Violation] | list[Violation]) -> dict[str, int]:
    """Debt breakdown by rule family — printed on ``--write-baseline`` so a
    1000+-entry baseline is a visible number per rule, not an opaque wall
    of JSON no reviewer will actually read end to end.
    """
    return dict(sorted(Counter(v.kind for v in violations).items()))
