#!/usr/bin/env python3
"""Generate the README's repo-derived badges as committed SVG files.

Why these badges are committed files and not hotlinked images
-------------------------------------------------------------
A remote badge URL (img.shields.io/...) is a third-party request fired on
every README view, and it lets its host restate our claim at any time with
no commit in this repository. A committed file cannot drift and cannot be
restated by anyone else.

Why only THESE badges
---------------------
Every figure below is determined BY THIS REPOSITORY: the licence, the
Python floor, the collected test count, the bibliography size, the package
version. So a committed copy can always be made true again by regenerating
it from the working tree, with no network access at all — which is why this
runs as a blocking CI check on every push and PR (`--check`) rather than on
a cron. Drift is caught where it is introduced.

Two README badges are deliberately NOT converted, and must not be:

  * The CI status badge reflects the LIVE result of the last run on main.
    A committed copy would assert "passing" while main was broken — a
    static build-status badge is a false claim by construction, not a stale
    one. It is also GitHub-hosted, so it is not a third-party beacon: the
    reader has already loaded the page from that same origin.
  * The OpenSSF Best Practices badge reflects an external body's live
    assessment, which can be downgraded without any commit here. Freezing
    it could over-claim a standing we no longer hold. .bestpractices.json
    additionally justifies displaying THEIR badge image, so replacing it
    with our own rendering would undercut that criterion.

The MCP Toplist badge sits between the two and IS committed, because it
carries an explicit "as of <month>" stamp: a stale copy remains a true
statement about a point in time. See refresh_mcp_toplist_badge.py.

Usage:
    python3 scripts/generate_repo_badges.py           # rewrite if changed
    python3 scripts/generate_repo_badges.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

# Sibling modules, path-imported for the same reason the launcher family
# does it: resolves identically whether this runs as a script or is loaded
# via importlib.util.spec_from_file_location from a test.
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
import badge_render  # noqa: E402
import check_doc_claims  # noqa: E402
import doc_claim_structural  # noqa: E402
import repo_badge_catalog  # noqa: E402

# Only the label/message palette repo_badge_svg() itself renders with, plus
# _HEALTHY (tests_py/scripts/test_generate_repo_badges.py reads
# gen._HEALTHY), are re-exported here; _NEUTRAL/_CORPUS are used only by
# repo_badge_catalog.fixed_badge_specs, which owns them (issue #287 split —
# see that module's docstring for why it returns field dicts, not
# RepoBadge instances, and never imports this class).
from repo_badge_catalog import _HEALTHY as _HEALTHY  # noqa: E402  (re-export)
from repo_badge_catalog import (  # noqa: E402
    _LABEL_FILL,
    _LABEL_TEXT,
    _MESSAGE_TEXT,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = Path("assets")


@dataclass(frozen=True)
class RepoBadge:
    """One generated badge: its file, its two panels, and its alt text.

    Data only — deliberately no methods. mutmut's mutation generator
    categorically excludes the body of any `@dataclass`-decorated class (it
    must, since copying a decorated class for the trampoline setup can
    re-run the decorator and its side effects), so logic placed on methods
    here would carry zero mutation coverage no matter how the test loader
    names the module. Confirmed empirically: 234 mutants for this file, 0
    attributed to `path`/`render` while they were methods (issue #262's
    3rd pass; same defect and same fix shape as `ConstraintSet` in
    scripts/pip_constraint_sets.py). `repo_badge_path`/`repo_badge_svg`
    below carry the same logic as free functions instead.
    """

    filename: str
    label: str
    message: str
    fill: str
    alt: str
    derivation: str


def repo_badge_path(repo_badge: RepoBadge) -> Path:
    return ASSETS_DIR / repo_badge.filename


def repo_badge_svg(repo_badge: RepoBadge) -> str:
    provenance = (
        "  <!-- GENERATED by scripts/generate_repo_badges.py — do not hand-edit.",
        f"       {repo_badge.derivation}",
        "       Committed rather than hotlinked so the claim cannot be",
        "       restated by a third party without a commit here; kept true",
        "       by the generate_repo_badges check, a blocking CI gate. -->",
    )
    spec = badge_render.BadgeSpec(
        label=badge_render.label_panel(repo_badge.label, _LABEL_FILL, _LABEL_TEXT),
        message=repo_badge.message,
        message_fill=repo_badge.fill,
        message_text_fill=_MESSAGE_TEXT,
        alt=repo_badge.alt,
        provenance=provenance,
    )
    return badge_render.render(spec)


def canonical_licence() -> str:
    """The licence name, from the packaging metadata that governs it."""
    text = check_doc_claims.read("pyproject.toml")
    for pattern in ('license = "', 'license = {text = "'):
        head, sep, tail = text.partition(pattern)
        if sep:
            # maxsplit=1 is not load-bearing: str.split(sep, n)[0] is the text
            # before the FIRST occurrence of sep for every n != 0 (mutation-
            # testing equivalence — 0, 1, 2, and -1/unbounded all agree here),
            # so this is the plain, un-tunable "up to the next quote" read.
            return tail.split('"', 1)[0]
    raise check_doc_claims.ClaimError("pyproject.toml: [project].license not found")


def canonical_python_floor() -> str:
    """The minimum supported Python, from requires-python."""
    text = check_doc_claims.read("pyproject.toml")
    head, sep, tail = text.partition('requires-python = ">=')
    if not sep:
        raise check_doc_claims.ClaimError(
            'pyproject.toml: requires-python ">=X.Y" not found'
        )
    # See canonical_licence's identical comment: maxsplit=1 is not load-bearing.
    return tail.split('"', 1)[0]


def build_badges(test_count: int | None) -> list[RepoBadge]:
    """Every repo-derived badge, resolved against the working tree.

    The canonical readers are check_doc_claims's own, not reimplementations:
    a badge that disagreed with the gate would be the exact drift this file
    exists to prevent. The field data itself lives in repo_badge_catalog.py
    (issue #287 split, §4: the 300-line file cap) — this function's own job
    is only to resolve the canonical values and construct `RepoBadge`
    instances from the returned specs.
    """
    version = check_doc_claims.canonical_version()
    references = check_doc_claims.canonical_reference_count()
    licence = canonical_licence()
    floor = canonical_python_floor()
    badges = [
        RepoBadge(**spec)
        for spec in repo_badge_catalog.fixed_badge_specs(
            licence, floor, references, version
        )
    ]
    # The test count is the one figure that cannot be read off a file: it is
    # whatever the suite collects right now. Omitted rather than guessed when
    # the caller has not measured it, so a stale badge is never written from
    # an assumption.
    if test_count is not None:
        badges.append(RepoBadge(**repo_badge_catalog.tests_badge_spec(test_count)))
    return badges


def write(badge: RepoBadge) -> bool:
    """Write the badge; True when the file changed."""
    target = REPO_ROOT / repo_badge_path(badge)
    rendered = repo_badge_svg(badge)
    if target.exists() and target.read_text(encoding="utf-8") == rendered:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    return True


def stale(badge: RepoBadge) -> str | None:
    """The reason this badge is out of date, or None when it is current."""
    target = REPO_ROOT / repo_badge_path(badge)
    if not target.exists():
        path = repo_badge_path(badge)
        return f"{path}: missing — run scripts/generate_repo_badges.py"
    if target.read_text(encoding="utf-8") != repo_badge_svg(badge):
        path = repo_badge_path(badge)
        return (
            f"{path}: stale ({badge.label} is now {badge.message!r})"
            " — run scripts/generate_repo_badges.py"
        )
    return None


def stale_tests_badge(test_count: int) -> str | None:
    """A monotone floor, not an exact snapshot (issue #287, §6): two
    branches adding tests compute two different, both-true live counts for
    the same post-merge tree, so an exact match is how any two such PRs
    conflicted on this file, and how main's gate flapped red on a merge
    that only grew the count. Lagging behind `test_count` is not reported;
    only an OVER-claim is. `stale()` still checks everything else exactly.
    See doc_claim_structural.check_badge_floor for the same invariant.
    """
    badge = RepoBadge(**repo_badge_catalog.tests_badge_spec(test_count))
    path = repo_badge_path(badge)
    target = REPO_ROOT / path
    if not target.exists():
        return f"{path}: missing — run scripts/generate_repo_badges.py"
    match = doc_claim_structural.TESTS_BADGE.search(target.read_text(encoding="utf-8"))
    if match is None:
        return f"{path}: no test-count figure in its <title>; diverged from this gate"
    committed_count = int(match.group(1))
    if committed_count > test_count:
        return (
            f"{path}: badge claims {committed_count} tests,"
            f" exceeding the live count of {test_count}"
        )
    return stale(RepoBadge(**repo_badge_catalog.tests_badge_spec(committed_count)))


def _build_parser() -> argparse.ArgumentParser:
    """Extracted so a test can assert its exact contract (description,
    per-flag help text, `--test-count`'s type) without re-parsing rendered
    `--help` output, which argparse re-wraps at word boundaries."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any badge is missing or stale",
    )
    parser.add_argument(
        "--test-count",
        type=int,
        # default=None is argparse's own default for an omitted `default`
        # kwarg (mutation-testing equivalence: removing this line changes
        # nothing observable), kept explicit as documentation of intent —
        # "no live count" is a real, tested state (see BuildTests).
        default=None,
        help="live test count (from `pytest --collect-only -q`); badge skipped"
        " when absent",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    # A gate that cannot READ its inputs is a different outcome from a gate
    # that read them and found drift: exit 2 keeps "could not run" from being
    # mistaken for "found a stale badge" by whatever reads this exit code.
    try:
        badges = build_badges(args.test_count)
    except (check_doc_claims.ClaimError, FileNotFoundError) as error:
        print(f"badge generation could not run: {error}", file=sys.stderr)
        return 2

    if args.check:
        # The tests badge is checked by stale_tests_badge (a monotone floor,
        # not an exact match — see its docstring); every other badge keeps
        # the plain, exact-match stale() unchanged.
        failures = [
            reason
            for badge in badges
            if badge.filename != repo_badge_catalog.TESTS_BADGE_FILENAME
            and (reason := stale(badge))
        ]
        if args.test_count is not None:
            reason = stale_tests_badge(args.test_count)
            if reason:
                failures.append(reason)
        if failures:
            print("Committed badges disagree with the repository:", file=sys.stderr)
            for failure in failures:
                print(f"  {failure}", file=sys.stderr)
            return 1
        print(f"badges OK ({len(badges)} checked)")
        return 0

    changed = [repo_badge_path(badge) for badge in badges if write(badge)]
    for path in changed:
        print(f"wrote {path}")
    print(f"{len(changed)} of {len(badges)} badge(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
