#!/usr/bin/env python3
"""Generate the README's repo-derived badges as committed SVG files.

Why these badges are committed files and not hotlinked images
-------------------------------------------------------------
A remote badge URL (img.shields.io/...) is a third-party request fired on
every README view, and it lets its host restate our claim at any time with
no commit in this repository. A committed file cannot drift and cannot be
restated by anyone else.

Why only THESE badges
---------------------
Every figure below is determined BY THIS REPOSITORY: the licence, the
Python floor, the collected test count, the bibliography size, the package
version. So a committed copy can always be made true again by regenerating
it from the working tree, with no network access at all — which is why this
runs as a blocking CI check on every push and PR (`--check`) rather than on
a cron. Drift is caught where it is introduced.

Two README badges are deliberately NOT converted, and must not be:

  * The CI status badge reflects the LIVE result of the last run on main.
    A committed copy would assert "passing" while main was broken — a
    static build-status badge is a false claim by construction, not a stale
    one. It is also GitHub-hosted, so it is not a third-party beacon: the
    reader has already loaded the page from that same origin.
  * The OpenSSF Best Practices badge reflects an external body's live
    assessment, which can be downgraded without any commit here. Freezing
    it could over-claim a standing we no longer hold. .bestpractices.json
    additionally justifies displaying THEIR badge image, so replacing it
    with our own rendering would undercut that criterion.

The MCP Toplist badge sits between the two and IS committed, because it
carries an explicit "as of <month>" stamp: a stale copy remains a true
statement about a point in time. See refresh_mcp_toplist_badge.py.

Usage:
    python3 scripts/generate_repo_badges.py           # rewrite if changed
    python3 scripts/generate_repo_badges.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

# Sibling modules, path-imported for the same reason the launcher family
# does it: resolves identically whether this runs as a script or is loaded
# via importlib.util.spec_from_file_location from a test.
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
import badge_render  # noqa: E402
import check_doc_claims  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = Path("assets")

# The palette is assets/banner.svg's, shared with the MCP Toplist badge so
# the README's badge row reads as one set rather than as a pile of styles.
_LABEL_FILL = "#3b3129"
_LABEL_TEXT = "#f8f7f2"
_MESSAGE_TEXT = "#fff"

# Message-panel fills. Distinct hues carry the same meaning the shields.io
# originals did (blue = neutral fact, green = healthy, orange = corpus), so
# the row's reading does not change with its hosting.
_NEUTRAL = "#31708f"
_HEALTHY = "#2f6f3e"
_CORPUS = "#a53e00"


@dataclass(frozen=True)
class RepoBadge:
    """One generated badge: its file, its two panels, and its alt text."""

    filename: str
    label: str
    message: str
    fill: str
    alt: str
    derivation: str

    def path(self) -> Path:
        return ASSETS_DIR / self.filename

    def render(self) -> str:
        provenance = (
            "  <!-- GENERATED by scripts/generate_repo_badges.py — do not hand-edit.",
            f"       {self.derivation}",
            "       Committed rather than hotlinked so the claim cannot be",
            "       restated by a third party without a commit here; kept true",
            "       by the generate_repo_badges check, a blocking CI gate. -->",
        )
        spec = badge_render.BadgeSpec(
            label=badge_render.label_panel(self.label, _LABEL_FILL, _LABEL_TEXT),
            message=self.message,
            message_fill=self.fill,
            message_text_fill=_MESSAGE_TEXT,
            alt=self.alt,
            provenance=provenance,
        )
        return badge_render.render(spec)


def canonical_licence() -> str:
    """The licence name, from the packaging metadata that governs it."""
    text = check_doc_claims.read("pyproject.toml")
    for pattern in ('license = "', 'license = {text = "'):
        head, sep, tail = text.partition(pattern)
        if sep:
            return tail.split('"', 1)[0]
    raise check_doc_claims.ClaimError("pyproject.toml: [project].license not found")


def canonical_python_floor() -> str:
    """The minimum supported Python, from requires-python."""
    text = check_doc_claims.read("pyproject.toml")
    head, sep, tail = text.partition('requires-python = ">=')
    if not sep:
        raise check_doc_claims.ClaimError(
            'pyproject.toml: requires-python ">=X.Y" not found'
        )
    return tail.split('"', 1)[0]


def build_badges(test_count: int | None) -> list[RepoBadge]:
    """Every repo-derived badge, resolved against the working tree.

    The canonical readers are check_doc_claims's own, not reimplementations:
    a badge that disagreed with the gate would be the exact drift this file
    exists to prevent.
    """
    version = check_doc_claims.canonical_version()
    references = check_doc_claims.canonical_reference_count()
    licence = canonical_licence()
    floor = canonical_python_floor()
    badges = [
        RepoBadge(
            filename="badge-license.svg",
            label="license",
            message=licence,
            fill=_NEUTRAL,
            alt=f"License: {licence}",
            derivation="Source: [project].license in pyproject.toml.",
        ),
        RepoBadge(
            filename="badge-python.svg",
            label="python",
            message=f"{floor}+",
            fill=_NEUTRAL,
            alt=f"Python {floor}+",
            derivation="Source: [project].requires-python in pyproject.toml.",
        ),
        RepoBadge(
            filename="badge-references.svg",
            label="references",
            message=f"{references} papers",
            fill=_CORPUS,
            alt=f"{references} referenced papers",
            derivation=(
                "Source: entries under '## References' in docs/papers/bibliography.md."
            ),
        ),
        RepoBadge(
            filename="badge-version.svg",
            label="version",
            message=version,
            fill=_HEALTHY,
            alt=f"Version {version}",
            derivation="Source: [project].version in pyproject.toml.",
        ),
    ]
    # The test count is the one figure that cannot be read off a file: it is
    # whatever the suite collects right now. Omitted rather than guessed when
    # the caller has not measured it, so a stale badge is never written from
    # an assumption.
    if test_count is not None:
        badges.append(
            RepoBadge(
                filename="badge-tests.svg",
                label="tests",
                message=f"{test_count} passing",
                fill=_HEALTHY,
                alt=f"{test_count} tests passing",
                derivation="Source: the count pytest collects on this tree.",
            )
        )
    return badges


def write(badge: RepoBadge) -> bool:
    """Write the badge; True when the file changed."""
    target = REPO_ROOT / badge.path()
    rendered = badge.render()
    if target.exists() and target.read_text(encoding="utf-8") == rendered:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    return True


def stale(badge: RepoBadge) -> str | None:
    """The reason this badge is out of date, or None when it is current."""
    target = REPO_ROOT / badge.path()
    if not target.exists():
        return f"{badge.path()}: missing — run scripts/generate_repo_badges.py"
    if target.read_text(encoding="utf-8") != badge.render():
        return (
            f"{badge.path()}: stale ({badge.label} is now {badge.message!r})"
            " — run scripts/generate_repo_badges.py"
        )
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any badge is missing or stale",
    )
    parser.add_argument(
        "--test-count",
        type=int,
        default=None,
        help="live test count (from `pytest --collect-only -q`); badge skipped"
        " when absent",
    )
    args = parser.parse_args(argv)

    # A gate that cannot READ its inputs is a different outcome from a gate
    # that read them and found drift: exit 2 keeps "could not run" from being
    # mistaken for "found a stale badge" by whatever reads this exit code.
    try:
        badges = build_badges(args.test_count)
    except (check_doc_claims.ClaimError, FileNotFoundError) as error:
        print(f"badge generation could not run: {error}", file=sys.stderr)
        return 2

    if args.check:
        failures = [reason for badge in badges if (reason := stale(badge))]
        if failures:
            print("Committed badges disagree with the repository:", file=sys.stderr)
            for failure in failures:
                print(f"  {failure}", file=sys.stderr)
            return 1
        print(f"badges OK ({len(badges)} checked)")
        return 0

    changed = [badge.path() for badge in badges if write(badge)]
    for path in changed:
        print(f"wrote {path}")
    print(f"{len(changed)} of {len(badges)} badge(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
