#!/usr/bin/env python3
"""The table of hash-pinned requirements files and what reads each one.

Pure data plus the uv invocation each entry implies: no subprocess, no
filesystem, no network. The engine that runs uv, derives index directives
from uv.lock and writes the files is scripts/generate_pip_constraints.py.
Keeping the table separable is what lets a test assert the mapping without
a uv on PATH, and what keeps either file under the 300-line cap.

Why one file per call site
--------------------------
A job must install what it tests and no more. Handing every job a single
superset would silently change what the SQLite job exercises (it would
acquire psycopg) and would enlarge the supply-chain surface of the lint job
to that of the full test matrix. Each entry below names its consumers, and
the engine's `--check` fails when a file and the lock disagree.

Adding a set is one entry in SETS — no edit to the engine (§1.2).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

REQUIREMENTS_DIR = Path("requirements")


@dataclass(frozen=True)
class ConstraintSet:
    """One hash-pinned requirements file and the call sites that read it."""

    filename: str
    consumers: tuple[str, ...]
    extras: tuple[str, ...] = ()
    groups: tuple[str, ...] = ()
    only_groups: tuple[str, ...] = ()
    note: str = ""

    def path(self) -> Path:
        return REQUIREMENTS_DIR / self.filename

    def command(self) -> list[str]:
        """The uv invocation whose stdout IS this file.

        `--locked` and not `--frozen`: `--frozen` exports whatever the lock
        happens to say, so a pyproject.toml edited but never re-locked would
        still export cleanly and `--check` would stay green over files
        describing a dependency set nobody declared. `--locked` fails
        instead, naming `uv lock` as the fix.

        Captured from stdout and never via `-o`: uv writes the invoking
        command into the file header, and an `-o` path would embed an
        absolute, machine-specific path and destroy determinism.
        """
        cmd = [
            "uv",
            "export",
            "--locked",
            "--no-emit-project",
            "--no-default-groups",
            "--format",
            "requirements.txt",
        ]
        for extra in self.extras:
            cmd += ["--extra", extra]
        for group in self.groups:
            cmd += ["--group", group]
        for group in self.only_groups:
            cmd += ["--only-group", group]
        return cmd

    def header_lines(self) -> list[str]:
        """Provenance a reader hits before the first hash."""
        lines = [
            "#" * 74,
            "# GENERATED by scripts/generate_pip_constraints.py — do not hand-edit.",
            "#",
            "# Source of truth: uv.lock. Regenerate with",
            "#     python3 scripts/generate_pip_constraints.py",
            "# and commit the result; CI re-runs it with --check and fails on drift.",
            "#",
            "# Read by:",
        ]
        lines += [f"#   {consumer}" for consumer in self.consumers]
        if self.note:
            lines += ["#"] + [f"# {line}" for line in self.note.strip().splitlines()]
        lines.append("#" * 74)
        return lines


# Every pip install in this repository reads one of these. The mapping is
# asserted by tests_py/scripts/test_generate_pip_constraints.py in both
# directions, so neither a set without a file nor a file without a set can
# survive — an orphaned file is one `--check` would never notice going stale.
SETS: tuple[ConstraintSet, ...] = (
    ConstraintSet(
        filename="ci-postgresql.txt",
        consumers=(".github/workflows/ci.yml — Test (Python 3.x), PostgreSQL matrix",),
        extras=("dev", "postgresql", "codebase"),
    ),
    ConstraintSet(
        filename="ci-sqlite.txt",
        consumers=(".github/workflows/ci.yml — Test (SQLite backend)",),
        extras=("dev", "sqlite", "codebase"),
    ),
    ConstraintSet(
        filename="ci-sqlite-min.txt",
        consumers=(".github/workflows/ci.yml — Test (Windows, SQLite backend)",),
        extras=("dev", "sqlite"),
        note=(
            "Deliberately without the codebase extra: the Windows job proves the"
            " SQLite backend stands up with no tree-sitter toolchain present."
        ),
    ),
    ConstraintSet(
        filename="ci-typecheck.txt",
        consumers=(".github/workflows/ci.yml — Type Check",),
        extras=("dev", "postgresql", "sqlite", "codebase", "otel"),
        note=(
            "The widest extra set on purpose: pyright resolves imports across"
            " every optional backend, so a narrower install would report"
            " missing-import errors that say nothing about the code."
        ),
    ),
    ConstraintSet(
        filename="release.txt",
        consumers=(".github/workflows/release.yml — verification job",),
        extras=("dev", "postgresql"),
    ),
    ConstraintSet(
        filename="lint.txt",
        consumers=(".github/workflows/ci.yml — Lint",),
        only_groups=("lint",),
    ),
    ConstraintSet(
        filename="typecheck-tool.txt",
        consumers=(".github/workflows/ci.yml — Type Check (pyright itself)",),
        only_groups=("typecheck",),
        note=(
            "Separate from ci-typecheck.txt because pyright installs into its"
            " own environment, not the one it analyses."
        ),
    ),
    ConstraintSet(
        filename="packaging.txt",
        consumers=(
            ".github/workflows/ci.yml — Build Package",
            ".github/workflows/release.yml — build job",
        ),
        only_groups=("packaging",),
    ),
    ConstraintSet(
        filename="fuzz.txt",
        consumers=(".github/workflows/fuzz.yml — ClusterFuzzLite batch run",),
        only_groups=("fuzz",),
        note=(
            "Resolves to nothing outside linux/x86_64/cpython>=3.12 — that is"
            " atheris's entire published wheel matrix, not a hedge."
        ),
    ),
    ConstraintSet(
        filename="runtime-postgresql.txt",
        consumers=("Dockerfile — builder stage",),
        extras=("postgresql",),
        groups=("container",),
        note=(
            "The container group pulls torch from the PyTorch CPU index (see"
            " [tool.uv.sources] in pyproject.toml), so this file's torch hashes"
            " are the +cpu wheels — not the ~2GB CUDA build PyPI serves."
        ),
    ),
    ConstraintSet(
        filename="devcontainer.txt",
        consumers=(".devcontainer/Dockerfile",),
        extras=("postgresql", "codebase"),
        groups=("container",),
    ),
    ConstraintSet(
        filename="docker-runtime.txt",
        consumers=("docker/Dockerfile — builder stage",),
        extras=("postgresql", "codebase"),
        groups=("container",),
    ),
    ConstraintSet(
        filename="setup.txt",
        consumers=("scripts/setup.sh",),
        extras=("postgresql", "codebase", "benchmarks"),
        note=(
            "Replaces a hand-written package list that had already drifted from"
            " pyproject.toml. The benchmarks extra is what carries datasets,"
            " which that list installed."
        ),
    ),
)
