#!/usr/bin/env python3
"""Regenerate assets/badge-mcp-toplist.svg from upstream MCP Toplist data.

The badge is a committed static file, not a hotlinked remote image, so it
cannot restate itself without a commit in our history. The cost of that
choice is that it cannot self-update: the date it carries is part of the
claim, and goes stale by INACTION. Inaction never opens a PR, so this
script exists to be run on a cron and propose the refresh.

The data acquisition (fetch, the two parser strategies, and shared
validation) lives in the sibling module mcp_toplist_ranking.py — see its
docstring for the two extraction paths and their fallback order. This
file re-exports every one of its public names (`import X as X`, mirroring
condensers.py's issue #228 facade), so every existing import path and
test-patch target keeps resolving unchanged; the split is an internal
reorganization; this file's own job is rendering the SVG and the CLI.

Usage:
    python3 scripts/refresh_mcp_toplist_badge.py           # rewrite if changed
    python3 scripts/refresh_mcp_toplist_badge.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from datetime import date, datetime, timezone
from pathlib import Path

# badge_render.py and mcp_toplist_ranking.py are stdlib-only sibling
# modules. Path-based import for the same reason the launcher family
# path-imports its siblings: resolves identically whether this file is run
# as a script (script dir already on sys.path) or loaded directly via
# importlib.util.spec_from_file_location from a test.
_SCRIPTS_DIR = str(Path(__file__).resolve().parent)
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
import badge_render  # noqa: E402
from mcp_toplist_ranking import LEADERBOARD_URL as LEADERBOARD_URL  # noqa: E402
from mcp_toplist_ranking import SERVER_ID as SERVER_ID  # noqa: E402
from mcp_toplist_ranking import SERVER_PAGE_URL as SERVER_PAGE_URL  # noqa: E402
from mcp_toplist_ranking import TIMEOUT_S as TIMEOUT_S  # noqa: E402
from mcp_toplist_ranking import Ranking as Ranking  # noqa: E402
from mcp_toplist_ranking import UpstreamError as UpstreamError  # noqa: E402
from mcp_toplist_ranking import fetch as fetch  # noqa: E402
from mcp_toplist_ranking import parse_leaderboard as parse_leaderboard  # noqa: E402
from mcp_toplist_ranking import parse_server_page as parse_server_page  # noqa: E402
from mcp_toplist_ranking import ranking_percentile as ranking_percentile  # noqa: E402
from mcp_toplist_ranking import ranking_tier_text as ranking_tier_text  # noqa: E402
from mcp_toplist_ranking import resolve_ranking as resolve_ranking  # noqa: E402
from mcp_toplist_ranking import validate as validate  # noqa: E402

BADGE_PATH = Path("assets/badge-mcp-toplist.svg")

# The left panel carries the fixed string "MCP Toplist", so unlike the right
# panel its geometry never varies with the data. Both measured 2026-07-28 by
# rendering: 64px of text inside a 92px panel (icon + padding).
_LABEL_TEXT_W = 64
_LABEL_PANEL_W = 92

# Locale-independent: strftime("%b") follows the runner's locale, which is
# not pinned across GitHub-hosted images.
_MONTHS = (
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
)


def _provenance_comment(ranking: Ranking, as_of: date) -> list[str]:
    """The audit trail the badge carries in its own source.

    Whoever next bumps this file must be able to re-derive the claim from
    the file alone: where the figure came from, the raw inputs, the
    arithmetic, and what the number does NOT assert.
    """
    pct = ranking.rank / ranking.total * 100
    return [
        "  <!-- GENERATED by scripts/refresh_mcp_toplist_badge.py — do not hand-edit.",
        f"       Source: {ranking.source} reported rank {ranking.rank:,}"
        f" of {ranking.total:,}",
        f"       tracked MCP servers, read {as_of.isoformat()}",
        f"       ({ranking.rank}/{ranking.total} = {pct:.2f}%"
        f' -> "{ranking_tier_text(ranking)}").',
        f"       Verify: {SERVER_PAGE_URL}",
        "       Upstream's score is a popularity and activity signal, not a quality",
        "       assessment, and ~25% of its weighting is undisclosed — so this badge",
        "       says Cortex is RANKED in this tier by MCP Toplist, never that"
        " it IS. -->",
    ]


def render_badge(ranking: Ranking, as_of: date) -> str:
    """Render the badge SVG.

    Geometry, escaping and the no-<style>/no-external-font constraints live
    in badge_render; what stays here is what makes this badge THIS badge —
    the bar icon, the banner palette, and the wording of the claim.
    """
    tier = ranking_tier_text(ranking)
    stamp = f"{_MONTHS[as_of.month - 1]} {as_of.year}"
    alt = f"MCP Toplist: {tier} of {ranking.total:,} tracked MCP servers, {stamp}"
    label = badge_render.Panel(
        text="MCP Toplist",
        fill="#3b3129",
        text_fill="#f8f7f2",
        # Explicit, not derived: the bar icon displaces the label text, so
        # this panel is not centred on its own midpoint.
        width=_LABEL_PANEL_W,
        text_width=_LABEL_TEXT_W,
        text_x=54,
    )
    spec = badge_render.BadgeSpec(
        label=label,
        message=f"{tier} · {stamp}",
        message_fill="#a53e00",
        message_text_fill="#fff",
        alt=alt,
        provenance=tuple(_provenance_comment(ranking, as_of)),
        icon=(
            '  <g fill="#f1eee7">',
            '    <rect x="7" y="10" width="2.6" height="5" rx="0.6"/>',
            '    <rect x="11.2" y="6.5" width="2.6" height="8.5" rx="0.6"/>',
            '    <rect x="15.4" y="8.4" width="2.6" height="6.6" rx="0.6"/>',
            "  </g>",
        ),
    )
    return badge_render.render(spec)


def _today() -> date:
    return datetime.now(timezone.utc).date()


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the badge is out of date; never write",
    )
    parser.add_argument("--badge", type=Path, default=BADGE_PATH)
    return parser


def _ranking_summary(ranking: Ranking) -> str:
    """The one-line summary shared by the current/updated messages."""
    return (
        f"{ranking_tier_text(ranking)} "
        f"(#{ranking.rank:,} of {ranking.total:,}, via {ranking.source})"
    )


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    try:
        ranking, notices = resolve_ranking()
    except UpstreamError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    for notice in notices:
        print(f"notice: fell back after: {notice}", file=sys.stderr)

    rendered = render_badge(ranking, _today())
    current = args.badge.read_text() if args.badge.exists() else None

    if current == rendered:
        print(f"current: {_ranking_summary(ranking)}")
        return 0

    if args.check:
        print(
            f"STALE: badge does not match upstream "
            f"({ranking_tier_text(ranking)}, #{ranking.rank:,} of {ranking.total:,})",
            file=sys.stderr,
        )
        return 1

    args.badge.write_text(rendered)
    print(f"updated: {_ranking_summary(ranking)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
